const NO_CONTEXT_REPLY_I18N = {
  english: "Information not found in uploaded reports.",
  gujarati: "અપલોડ કરેલા અહેવાલોમાં આ માહિતી મળી નથી.",
  hindi: "अपलोड की गई रिपोर्ट में यह जानकारी नहीं मिली।",
  marathi: "अपलोड केलेल्या अहवालात ही माहिती आढळली नाही.",
  tamil: "பதிவேற்றப்பட்ட அறிக்கைகளில் இந்தத் தகவல் காணப்படவில்லை.",
};

const REQUIRE_SELECTION_I18N = {
  english: "Sure, please select your document that you have to compare.",
  gujarati: "ચોક્કસ, કૃપા કરીને તમારો દસ્તાવેજ પસંદ કરો જેની તમારે સરખામણી કરવી છે.",
  hindi: "ज़रूर, कृपया अपने उस दस्तावेज़ का चयन करें जिसकी आपको तुलना करनी है।",
  marathi: "नक्की, कृपया तुमचा दस्तऐवज निवडा ज्याची तुम्हाला तुलना करायची आहे.",
  tamil: "நிச்சயமாக, தயவுசெய்து நீங்கள் ஒப்பிட வேண்டிய உங்கள் ஆவணத்தைத் தேர்ந்தெடுக்கவும்.",
};

const AGE_REPLY_I18N = {
  english: {
    success: (dobStr, age) => `Based on your date of birth (${dobStr}), you are ${age} years old.`,
    missing: "Your date of birth is not specified in your profile, so I cannot calculate your age.",
  },
  gujarati: {
    success: (dobStr, age) => `તમારી જન્મ તારીખ (${dobStr}) ના આધારે, તમારી ઉંમર ${age} વર્ષ છે.`,
    missing:
      "તમારી જન્મ તારીખ તમારી પ્રોફાઇલમાં નિર્દિષ્ટ નથી, તેથી હું તમારી ઉંમરની ગણતરી કરી શકતો નથી.",
  },
  hindi: {
    success: (dobStr, age) => `आपकी जन्म तिथि (${dobStr}) के आधार पर, आपकी आयु ${age} वर्ष है।`,
    missing:
      "आपकी जन्म तिथि आपकी प्रोफ़ाइल में निर्दिष्ट नहीं है, इसलिए मैं आपकी आयु की गणना नहीं कर सकता।",
  },
  marathi: {
    success: (dobStr, age) => `तुमच्या जन्मतारखेनुसार (${dobStr}), तुमचे वय ${age} वर्षे आहे.`,
    missing:
      "तुमची जन्मतारीख तुमच्या प्रोफाइलमध्ये नमूद केलेली नाही, त्यामुळे मी तुमच्या वयाची गणना करू शकत नाही.",
  },
  tamil: {
    success: (dobStr, age) =>
      `உங்கள் பிறந்த தேதியின் (${dobStr}) அடிப்படையில், உங்கள் வயது ${age} ஆண்டுகள் ஆகும்.`,
    missing:
      "உங்கள் பிறந்த தேதி உங்கள் சுயவிவரத்தில் குறிப்பிடப்படவில்லை, எனவே என்னால் உங்கள் வயதைக் கணக்கிடுமாறு செய்ய முடியாது.",
  },
};

const SUMMARY_LABELS_I18N = {
  english: {
    patientName: "Patient Name",
    reportAge: "Report Age",
    summaryTitle: "Report Summary",
  },
  gujarati: {
    patientName: "દર્દીનું નામ",
    reportAge: "રિપોર્ટનો સમય",
    summaryTitle: "રિપોર્ટનો સારાંશ",
  },
  hindi: {
    patientName: "मरीज का नाम",
    reportAge: "रिपोर्ट की अवधि",
    summaryTitle: "रिपोर्ट का सारांश",
  },
  marathi: {
    patientName: "रुग्णाचे नाव",
    reportAge: "अहवालाचा कालावधी",
    summaryTitle: "अहवालाचा सारांश",
  },
  tamil: {
    patientName: "நோயாளி பெயர்",
    reportAge: "அறிக்கையின் வயது",
    summaryTitle: "அறிக்கையின் சுருக்கம்",
  },
};

const REPORT_PROCESSING_I18N = {
  english: "Your report is currently being processed. Please wait a moment.",
  gujarati: "તમારો રિપોર્ટ હાલમાં પ્રક્રિયા હેઠળ છે. કૃપા કરીને થોડી રાહ જુઓ.",
  hindi: "आपकी रिपोर्ट पर अभी प्रक्रिया चल रही है। कृपया कुछ समय प्रतीक्षा करें।",
  marathi: "तुमच्या अहवालावर सध्या प्रक्रिया सुरू आहे. कृपया काही वेळ थांबा.",
  tamil:
    "உங்கள் அறிக்கை தற்போது செயலாக்கப்பட்டு வருகிறது. தயவுசெய்து சிறிது நேரம் காத்திருக்கவும்.",
};

const NO_REPORT_FOUND_I18N = {
  english: "No active medical reports found in your profile.",
  gujarati: "તમારી પ્રોફાઇલમાં કોઈ સક્રિય તબીબી રિપોર્ટ મળ્યા નથી.",
  hindi: "आपकी प्रोफ़ाइल में कोई सक्रिय मेडिकल रिपोर्ट नहीं मिली।",
  marathi: "तुमच्या प्रोफाइलमध्ये कोणताही सक्रिय वैद्यकीय अहवाल आढळला नाही.",
  tamil: "உங்கள் சுயவிவரத்தில் செயலில் உள்ள மருத்துவ அறிக்கைகள் எதுவும் காணப்படவில்லை.",
};

const NO_SUMMARY_AVAILABLE_I18N = {
  english: "No summary details were found in this report.",
  gujarati: "આ રિપોર્ટમાં કોઈ સારાંશ વિગતો મળી નથી.",
  hindi: "इस रिपोर्ट में कोई सारांश विवरण नहीं मिला।",
  marathi: "या अहवालात कोणताही सारांश तपशील आढळला नाही.",
  tamil: "இந்த அறிக்கையில் சுருக்க விவரங்கள் எதுவும் காணப்படவில்லை.",
};

const AGE_KEYWORDS = [
  // English
  "what is my age",
  "how old am i",
  "calculate my age",
  // Gujarati
  "મારી ઉંમર શું છે",
  "મારી ઉંમર કેટલી છે",
  "હું કેટલા વર્ષનો છું",
  // Hindi
  "मेरी उम्र क्या है",
  "मेरी आयु क्या है",
  "मैं कितने साल का हूँ",
  // Marathi
  "माझे वय काय आहे",
  "माझे वय किती आहे",
  "मी किती वर्षांचा आहे",
  // Tamil
  "என் வயது என்ன",
  "எனக்கு என்ன வயது",
  "என் வயது எவ்வளவு",
];

const SUMMARY_KEYWORDS = [
  // English
  "ask_report",
  "ask report",
  "tell me about my report",
  "summary of my report",
  "report summary",
  "summarize my report",
  "explain my report",
  "tell me about report",
  "give me report summary",
  // Gujarati
  "રિપોર્ટ નો સારાંશ",
  "મને મારા રિપોર્ટ વિશે કહો",
  "મારો રિપોર્ટ સમજાવો",
  "રિપોર્ટ સમજાવો",
  "રિપોર્ટ નો સારાંશ આપો",
  "મારા રિપોર્ટ વિશે જણાવો",
  // Hindi
  "मेरी रिपोर्ट का सारांश",
  "मुझे मेरी रिपोर्ट के बारे में बताएं",
  "रिपोर्ट का सारांश",
  "मेरी रिपोर्ट समझाएं",
  "मेरी रिपोर्ट का सारांश दें",
  "मुझे रिपोर्ट के बारे में बताएं",
  // Marathi
  "માझ्या અહવાલાચા સારાંશ",
  "मला माझ्या अहवालाबद्दल सांगा",
  "અહવાલાચા સારાંશ",
  "માઝા અહવાલ સ્પષ્ટ કરા",
  "માझ्या અહવાલાચા સારાંશ દ્યા",
  "माझा अहवाल स्पष्ट करा",
  "माझ्या अहवालाचा सारांश द्या",
  // Tamil
  "என் அறிக்கையின் சுருக்கம்",
  "என் அறிக்கை பற்றி சொல்லுங்கள்",
  "அறிக்கையின் சுருக்கம்",
  "என் அறிக்கையை விளக்குங்கள்",
  "என் அறிக்கையின் சுருக்கத்தை கொடுங்கள்",
];

const PREDEFINED_QUESTIONS_I18N = {
  english: [
    "What are the key findings?",
    "Are there any abnormal values?",
    "What are the next steps or recommendations?",
  ],
  gujarati: [
    "મુખ્ય તારણો શું છે?",
    "શું કોઈ અસામાન્ય મૂલ્યો છે?",
    "આગળના પગલાં અથવા ભલામણો શું છે?",
  ],
  hindi: [
    "मुख्य निष्कर्ष क्या हैं?",
    "क्या कोई असामान्य मूल्य हैं?",
    "आगे के कदम या सिफारिशें क्या हैं?",
  ],
  marathi: [
    "मुख्य निष्कर्ष काय आहेत?",
    "काही असामान्य मूल्ये आहेत का?",
    "पुढील पावले किंवा शिफारसी काय आहेत?",
  ],
  tamil: [
    "முக்கிய கண்டுபிடிப்புகள் யாவை?",
    "ஏதேனும் அசாதாரண மதிப்புகள் உள்ளதா?",
    "அடுத்த படிகள் அல்லது பரிந்துரைகள் யாவை?",
  ],
};

const PROFILE_REPLY_I18N = {
  english: {
    title: "Official Profile Details:",
    name: "Name",
    email: "Email",
    mobile: "Mobile",
    dob: "Date of Birth",
    gender: "Gender",
    bloodGroup: "Blood Group",
    allergies: "Allergies",
    loginMethod: "Login Method",
    none: "None",
    notSpecified: "Not specified",
    unknown: "Unknown",
    specificName: (name) => `Your registered name is ${name}.`,
    specificBloodGroup: (bg) => `Your blood group is ${bg}.`,
    specificAllergies: (allergies) => `Your recorded allergies: ${allergies}.`,
    specificEmail: (email) => `Your registered email is ${email}.`,
    specificMobile: (mobile) => `Your registered mobile number is ${mobile}.`,
    specificLoginMethod: (method) => `You are logged in using ${method}.`,
    specificDob: (dob) => `Your registered date of birth is ${dob}.`,
    specificPatientCode: (code) => `Your patient code is ${code}.`,
    specificGender: (gender) => `Your registered gender is ${gender}.`,
  },
  gujarati: {
    title: "સત્તાવાર પ્રોફાઇલ વિગતો:",
    name: "નામ",
    email: "ઇમેઇલ",
    mobile: "મોબાઇલ",
    dob: "જન્મ તારીખ",
    gender: "જાતિ",
    bloodGroup: "બ્લડ ગ્રુપ",
    allergies: "એલર્જી",
    loginMethod: "લોગિન રીત",
    none: "કોઈ નહીં",
    notSpecified: "નિર્દિષ્ટ નથી",
    unknown: "અજ્ઞાત",
    specificName: (name) => `તમારું નોંધાયેલ નામ ${name} છે.`,
    specificBloodGroup: (bg) => `તમારું બ્લડ ગ્રુપ ${bg} છે.`,
    specificAllergies: (allergies) => `તમારી નોંધાયેલ એલર્જી: ${allergies}.`,
    specificEmail: (email) => `તમારો નોંધાયેલ ઇમેઇલ ${email} છે.`,
    specificMobile: (mobile) => `તમારો નોંધાયેલ મોબાઇલ નંબર ${mobile} છે.`,
    specificLoginMethod: (method) => `તમે ${method} વડે લોગિન કરેલ છો.`,
    specificDob: (dob) => `તમારી નોંધાયેલ જન્મ તારીખ ${dob} છે.`,
    specificPatientCode: (code) => `તમારો દર્દી કોડ ${code} છે.`,
    specificGender: (gender) => `તમારી નોંધાયેલ જાતિ ${gender} છે.`,
  },
  hindi: {
    title: "आधिकारिक प्रोफ़ाइल विवरण:",
    name: "नाम",
    email: "ईमेल",
    mobile: "मोबाइल",
    dob: "जन्म तिथि",
    gender: "लिंग",
    bloodGroup: "ब्लड ग्रुप",
    allergies: "एलर्जी",
    loginMethod: "लॉगिन का प्रकार",
    none: "कोई नहीं",
    notSpecified: "निर्दिष्ट नहीं",
    unknown: "अज्ञात",
    specificName: (name) => `आपका पंजीकृत नाम ${name} है।`,
    specificBloodGroup: (bg) => `आपका ब्लड ग्रुप ${bg} है।`,
    specificAllergies: (allergies) => `आपकी दर्ज एलर्जी: ${allergies}।`,
    specificEmail: (email) => `आपका पंजीकृत ईमेल ${email} है।`,
    specificMobile: (mobile) => `आपका पंजीकृत मोबाइल नंबर ${mobile} है।`,
    specificLoginMethod: (method) => `आप ${method} से लॉगिन हैं।`,
    specificDob: (dob) => `आपकी पंजीकृत जन्म तिथि ${dob} है।`,
    specificPatientCode: (code) => `आपका पेशेंट कोड ${code} है।`,
    specificGender: (gender) => `आपका पंजीकृत लिंग ${gender} है।`,
  },
  marathi: {
    title: "अधिकृत प्रोफाइल तपशील:",
    name: "नाव",
    email: "ईमेल",
    mobile: "मोबाइल",
    dob: "जन्मतारीख",
    gender: "लिंग",
    bloodGroup: "रक्तगट",
    allergies: "ऍलर्जी",
    loginMethod: "लॉगिन पद्धत",
    none: "काही नाही",
    notSpecified: "नमूद नाही",
    unknown: "अज्ञात",
    specificName: (name) => `तुमचे नोंदणीकृत नाव ${name} आहे.`,
    specificBloodGroup: (bg) => `तुमचा रक्तगट ${bg} आहे.`,
    specificAllergies: (allergies) => `तुमची नोंदवलेली ऍलर्जी: ${allergies}.`,
    specificEmail: (email) => `तुमचा नोंदणीकृत ईमेल ${email} आहे.`,
    specificMobile: (mobile) => `तुमचा नोंदणीकृत मोबाइल नंबर ${mobile} आहे.`,
    specificLoginMethod: (method) => `तुम्ही ${method} द्वारे लॉगिन केले आहे.`,
    specificDob: (dob) => `तुमची नोंदणीकृत जन्मतारीख ${dob} आहे.`,
    specificPatientCode: (code) => `तुमचा रुग्ण कोड ${code} आहे.`,
    specificGender: (gender) => `तुमचे नोंदणीकृत लिंग ${gender} आहे.`,
  },
  tamil: {
    title: "அதிகாரப்பூர்வ சுயவிவர விவரங்கள்:",
    name: "பெயர்",
    email: "மின்னஞ்சல்",
    mobile: "மொபைல்",
    dob: "பிறந்த தேதி",
    gender: "பாலினம்",
    bloodGroup: "இரத்த வகை",
    allergies: "ஒவ்வாமைகள்",
    loginMethod: "லாகின் முறை",
    none: "எதுவுமில்லை",
    notSpecified: "குறிப்பிடப்படவில்லை",
    unknown: "தெரியவில்லை",
    specificName: (name) => `உங்கள் பதிவு செய்யப்பட்ட பெயர் ${name}.`,
    specificBloodGroup: (bg) => `உங்கள் இரத்த வகை ${bg}.`,
    specificAllergies: (allergies) => `உங்கள் பதிவு செய்யப்பட்ட ஒவ்வாமைகள்: ${allergies}.`,
    specificEmail: (email) => `உங்கள் பதிவு செய்யப்பட்ட மின்னஞ்சல் ${email}.`,
    specificMobile: (mobile) => `உங்கள் பதிவு செய்யப்பட்ட மொபைல் எண் ${mobile}.`,
    specificLoginMethod: (method) => `நீங்கள் ${method} மூலம் உள்நுழைந்துள்ளீர்கள்.`,
    specificDob: (dob) => `உங்கள் பதிவு செய்யப்பட்ட பிறந்த தேதி ${dob}.`,
    specificPatientCode: (code) => `உங்கள் நோயாளி குறியீடு ${code}.`,
    specificGender: (gender) => `உங்கள் பதிவு செய்யப்பட்ட பாலினம் ${gender}.`,
  },
};

const REMINDER_REPLY_I18N = {
  english: {
    title: "Today's Medication Reminders:",
    titleToday: "Today's Medication Reminders:",
    titleTomorrow: "Tomorrow's Medication Reminders:",
    titleYesterday: "Yesterday's Medication Reminders:",
    titleMissed: "Missed Medication Reminders:",
    titleOverdue: "Overdue Medication Reminders:",
    titleNext: "Next Medication Reminder:",
    titleNeedToTake: "Medications to Take Today:",
    titleAtTime: (t) => `Medication Reminders at ${t}:`,
    total: "Total Scheduled Doses",
    taken: "Taken",
    pending: "Pending",
    missed: "Missed",
    noReminders: "You have no medication reminders scheduled for today.",
    noRemindersToday: "You have no medication reminders scheduled for today.",
    noRemindersTomorrow: "You have no medication reminders scheduled for tomorrow.",
    noRemindersYesterday: "You have no medication reminders recorded for yesterday.",
    noMissedReminders: "You have no missed medication reminders.",
    noOverdueReminders: "You have no overdue medication reminders.",
    noNextReminder: "You have no upcoming medication reminders scheduled.",
    noNeedToTake: "You have no pending medications to take today.",
    noReminderAtTime: (t) => `You have no reminders scheduled at ${t}.`,
    noRemindersDate: (d) => `You have no medication reminders recorded for ${d}.`,
    food: "Food",
    status: "Status",
  },
  gujarati: {
    title: "આજના દવાના રિમાઇન્ડર્સ:",
    titleToday: "આજના દવાના રિમાઇન્ડર્સ:",
    titleTomorrow: "આવતીકાલના દવાના રિમાઇન્ડર્સ:",
    titleYesterday: "ગઈકાલના દવાના રિમાઇન્ડર્સ:",
    titleMissed: "ચૂકી ગયેલા દવાના રિમાઇન્ડર્સ:",
    titleOverdue: "ઓવરડ્યુ (બાકી) દવાના રિમાઇન્ડર્સ:",
    titleNext: "આગામી દવાનું રિમાઇન્ડર:",
    titleNeedToTake: "આજે લેવાની દવાઓ:",
    titleAtTime: (t) => `${t} વાગ્યાના દવાના રિમાઇન્ડર્સ:`,
    total: "કુલ નિર્ધારિત ડોઝ",
    taken: "લીધેલ",
    pending: "બાકી",
    missed: "ચૂકી ગયેલ",
    noReminders: "તમારી પાસે આજે કોઈ દવાનું રિમાઇન્ડર નિર્ધારિત નથી.",
    noRemindersToday: "તમારી પાસે આજે કોઈ દવાનું રિમાઇન્ડર નિર્ધારિત નથી.",
    noRemindersTomorrow: "આવતીકાલ માટે કોઈ દવાનું રિમાઇન્ડર નિર્ધારિત નથી.",
    noRemindersYesterday: "તમારી પાસે ગઈકાલ માટે કોઈ દવાનું રિમાઇન્ડર નોંધાયેલ નથી.",
    noMissedReminders: "તમે આજે કોઈ દવાનું રિમાઇન્ડર ચૂક્યા નથી.",
    noOverdueReminders: "તમારી પાસે કોઈ ઓવરડ્યુ રિમાઇન્ડર નથી.",
    noNextReminder: "તમારી પાસે કોઈ આગામી દવાનું રિમાઇન્ડર નથી.",
    noNeedToTake: "આજે લેવા માટે કોઈ બાકી દવા નથી.",
    noReminderAtTime: (t) => `${t} વાગ્યે કોઈ રિમાઇન્ડર નિર્ધારિત નથી.`,
    noRemindersDate: (d) => `તમારી પાસે ${d} માટે કોઈ દવાનું રિમાઇન્ડર નોંધાયેલ નથી.`,
    food: "ખોરાક",
    status: "સ્થિતિ",
  },
  hindi: {
    title: "आज के दवा रिमाइंडर:",
    titleToday: "आज के दवा रिमाइंडर:",
    titleTomorrow: "कल के दवा रिमाइंडर:",
    titleYesterday: "कल (बीते हुए) के दवा रिमाइंडर:",
    titleMissed: "छूटे हुए दवा रिमाइंडर:",
    titleOverdue: "अतिदेय (ओवरड्यू) दवा रिमाइंडर:",
    titleNext: "अगला दवा रिमाइंडर:",
    titleNeedToTake: "आज ली जाने वाली दवाइयां:",
    titleAtTime: (t) => `${t} के दवा रिमाइंडर:`,
    total: "कुल निर्धारित खुराक",
    taken: "ली गई",
    pending: "लंबित",
    missed: "छूटी हुई",
    noReminders: "आज के लिए आपकी कोई दवा रिमाइंडर निर्धारित नहीं है।",
    noRemindersToday: "आज के लिए आपकी कोई दवा रिमाइंडर निर्धारित नहीं है।",
    noRemindersTomorrow: "कल के लिए कोई दवा रिमाइंडर निर्धारित नहीं है।",
    noRemindersYesterday: "कल के लिए आपकी कोई दवा रिमाइंडर दर्ज नहीं है।",
    noMissedReminders: "आपका कोई दवा रिमाइंडर छूटा नहीं है।",
    noOverdueReminders: "आपका कोई ओवरड्यू रिमाइंडर नहीं है।",
    noNextReminder: "आपका कोई आगामी दवा रिमाइंडर निर्धारित नहीं है।",
    noNeedToTake: "आज लेने के लिए कोई लंबित दवा नहीं है।",
    noReminderAtTime: (t) => `${t} पर कोई रिमाइंडर निर्धारित नहीं है।`,
    noRemindersDate: (d) => `${d} के लिए आपकी कोई दवा रिमाइंडर दर्ज नहीं है।`,
    food: "भोजन",
    status: "स्थिति",
  },
  marathi: {
    title: "आजचे औषध स्मरणपत्रे:",
    titleToday: "आजचे औषध स्मरणपत्रे:",
    titleTomorrow: "उद्याचे औषध स्मरणपत्रे:",
    titleYesterday: "कालचे औषध स्मरणपत्रे:",
    titleMissed: "चुकलेले औषध स्मरणपत्रे:",
    titleOverdue: "प्रलंबित (ओव्हरड्यू) औषध स्मरणपत्रे:",
    titleNext: "पुढील औषध स्मरणपत्र:",
    titleNeedToTake: "आज घ्यायची औषधे:",
    titleAtTime: (t) => `${t} ची औषध स्मरणपत्रे:`,
    total: "एकूण नियोजित डोस",
    taken: "घेतलेले",
    pending: "प्रलंबित",
    missed: "चुकलेले",
    noReminders: "आजसाठी तुमचे कोणतेही औषध स्मरणपत्र नियोजित नाही.",
    noRemindersToday: "आजसाठी तुमचे कोणतेही औषध स्मरणपत्र नियोजित नाही.",
    noRemindersTomorrow: "उद्यासाठी कोणतेही औषध स्मरणपत्र नियोजित नाही.",
    noRemindersYesterday: "कालसाठी तुमचे कोणतेही औषध स्मरणपत्र नोंदवलेले नाही.",
    noMissedReminders: "तुमचे कोणतेही औषध स्मरणपत्र चुकलेले नाही.",
    noOverdueReminders: "तुमचे कोणतेही ओव्हरड्यू स्मरणपत्र नाही.",
    noNextReminder: "तुमचे कोणतेही पुढील औषध स्मरणपत्र नियोजित नाही.",
    noNeedToTake: "आज घेण्यासाठी कोणतेही प्रलंबित औषध नाही.",
    noReminderAtTime: (t) => `${t} वाजता कोणतेही स्मरणपत्र नियोजित नाही.`,
    noRemindersDate: (d) => `${d} साठी तुमचे कोणतेही औषध स्मरणपत्र नोंदवलेले नाही.`,
    food: "अन्न",
    status: "स्थिती",
  },
  tamil: {
    title: "இன்றைய மருந்து நினைவூட்டல்கள்:",
    titleToday: "இன்றைய மருந்து நினைவூட்டல்கள்:",
    titleTomorrow: "நாளைய மருந்து நினைவூட்டல்கள்:",
    titleYesterday: "நேற்றைய மருந்து நினைவூட்டல்கள்:",
    titleMissed: "தவறிய மருந்து நினைவூட்டல்கள்:",
    titleOverdue: "காலாவதியான (தாமதமான) மருந்து நினைவூட்டல்கள்:",
    titleNext: "அடுத்த மருந்து நினைவூட்டல்:",
    titleNeedToTake: "இன்று உட்கொள்ள வேண்டிய மருந்துகள்:",
    titleAtTime: (t) => `${t} மணிக்கு உள்ள மருந்து நினைவூட்டல்கள்:`,
    total: "மொத்த திட்டமிடப்பட்ட மருந்தளவுகள்",
    taken: "எடுத்துக்கொண்டவை",
    pending: "நிலுவையில் உள்ளவை",
    missed: "தவறவிட்டவை",
    noReminders: "இன்று உங்களுக்கு எந்த மருந்து நினைவூட்டல்களும் திட்டமிடப்படவில்லை.",
    noRemindersToday: "இன்று உங்களுக்கு எந்த மருந்து நினைவூட்டல்களும் திட்டமிடப்படவில்லை.",
    noRemindersTomorrow: "நாளை எந்த மருந்து நினைவூட்டல்களும் திட்டமிடப்படவில்லை.",
    noRemindersYesterday: "நேற்று உங்களுக்கு எந்த மருந்து நினைவூட்டல்களும் பதிவு செய்யப்படவில்லை.",
    noMissedReminders: "நீங்கள் எந்த மருந்து நினைவூட்டலையும் தவறவிடவில்லை.",
    noOverdueReminders: "உங்களுக்கு காலாவதியான நினைவூட்டல்கள் எதுவும் இல்லை.",
    noNextReminder: "வரவிருக்கும் மருந்து நினைவூட்டல்கள் எதுவும் திட்டமிடப்படவில்லை.",
    noNeedToTake: "இன்று எடுத்துக்கொள்ள நிலுவையில் உள்ள மருந்துகள் எதுவும் இல்லை.",
    noReminderAtTime: (t) => `${t} மணிக்கு எந்த நினைவூட்டலும் திட்டமிடப்படவில்லை.`,
    noRemindersDate: (d) =>
      `${d} அன்று உங்களுக்கு எந்த மருந்து நினைவூட்டல்களும் பதிவு செய்யப்படவில்லை.`,
    food: "உணவு",
    status: "நிலை",
  },
};

const REFILL_REPLY_I18N = {
  english: {
    title: "Medication Refill Status:",
    titleNeedRefill: "Medications Needing Refill:",
    titleLatestRefill: "Latest Medication Refill:",
    titleHistory: "Medication Refill History:",
    titleRecentlyRefilled: "Recently Refilled Medications:",
    lowStock: "Low Stock / Refill Needed:",
    sufficientStock: "All active medications have sufficient stock.",
    noMeds: "No active medications found to track refills.",
    noRefillsRecorded: "You have no recorded medication refills.",
    noRefillNeeded: "None of your medications currently need a refill.",
    refillsLeft: "Refills Recorded",
    remainingStock: "Remaining Stock",
    refillQuantity: "Quantity Added",
    refillDate: "Date",
    totalRefills: "Total Refills Recorded",
  },
  gujarati: {
    title: "દવા રિફિલ સ્થિતિ:",
    titleNeedRefill: "રિફિલની જરૂર હોય તેવી દવાઓ:",
    titleLatestRefill: "છેલ્લી દવા રિફિલ:",
    titleHistory: "દવા રિફિલ ઇતિહાસ:",
    titleRecentlyRefilled: "તાજેતરમાં રિફિલ કરેલી દવાઓ:",
    lowStock: "ઓછો જથ્થો / રિફિલ જરૂરી:",
    sufficientStock: "બધી ચાલુ દવાઓ પાસે પૂરતો જથ્થો છે.",
    noMeds: "રિફિલ ટ્રેક કરવા માટે કોઈ ચાલુ દવાઓ મળી નથી.",
    noRefillsRecorded: "તમારી પાસે કોઈ નોંધાયેલ રિફિલ નથી.",
    noRefillNeeded: "તમારી કોઈપણ દવાને હાલમાં રિફિલની જરૂર નથી.",
    refillsLeft: "નોંધાયેલ રિફિલ",
    remainingStock: "બાકી જથ્થો",
    refillQuantity: "ઉમેરેલો જથ્થો",
    refillDate: "તારીખ",
    totalRefills: "કુલ નોંધાયેલ રિફિલ",
  },
  hindi: {
    title: "दवा रिफिल स्थिति:",
    titleNeedRefill: "रिफिल की आवश्यकता वाली दवाइयां:",
    titleLatestRefill: "नवीनतम दवा रिफिल:",
    titleHistory: "दवा रिफिल इतिहास:",
    titleRecentlyRefilled: "हाल ही में रिफिल की गई दवाइयां:",
    lowStock: "कम स्टॉक / रिफिल की आवश्यकता:",
    sufficientStock: "सभी सक्रिय दवाओं का पर्याप्त स्टॉक है।",
    noMeds: "रिफिल ट्रैक करने के लिए कोई सक्रिय दवा नहीं मिली।",
    noRefillsRecorded: "आपकी कोई दर्ज रिफिल नहीं है।",
    noRefillNeeded: "आपकी किसी भी दवा को वर्तमान में रिफिल की आवश्यकता नहीं है।",
    refillsLeft: "दर्ज रिफिल",
    remainingStock: "बचा हुआ स्टॉक",
    refillQuantity: "जोड़ी गई मात्रा",
    refillDate: "तारीख",
    totalRefills: "कुल दर्ज रिफिल",
  },
  marathi: {
    title: "औषध रिफिल स्थिती:",
    titleNeedRefill: "रिफिल आवश्यक असलेली औषधे:",
    titleLatestRefill: "नवीनतम औषध रिफिल:",
    titleHistory: "औषध रिफिल इतिहास:",
    titleRecentlyRefilled: "नुकतीच रिफिल केलेली औषधे:",
    lowStock: "कमी साठा / रिफिल आवश्यक:",
    sufficientStock: "सर्व चालू औषधांचा पुरेसा साठा उपलब्ध आहे.",
    noMeds: "रिफिल ट्रॅक करण्यासाठी कोणतीही चालू औषधे आढळली नाहीत.",
    noRefillsRecorded: "तुमच्याकडे कोणतेही नोंदवलेले रिफिल नाही.",
    noRefillNeeded: "तुमच्या कोणत्याही औषधाला सध्या रिफिलची आवश्यकता नाही.",
    refillsLeft: "नोंदवलेले रिफिल",
    remainingStock: "उरलेला साठा",
    refillQuantity: "जोडलेले प्रमाण",
    refillDate: "तारीख",
    totalRefills: "एकूण नोंदवलेले रिफिल",
  },
  tamil: {
    title: "மருந்து மறு நிரப்பல் நிலை:",
    titleNeedRefill: "மறு நிரப்பல் தேவைப்படும் மருந்துகள்:",
    titleLatestRefill: "சமீபத்திய மருந்து மறு நிரப்பல்:",
    titleHistory: "மருந்து மறு நிரப்பல் வரலாறு:",
    titleRecentlyRefilled: "சமீபத்தில் மறு நிரப்பப்பட்ட மருந்துகள்:",
    lowStock: "குறைந்த இருப்பு / மறு நிரப்பல் தேவை:",
    sufficientStock: "அனைத்து மருந்துகளும் போதுமான இருப்பில் உள்ளன.",
    noMeds: "மறு நிரப்பலைக் கண்காணிக்க எந்த மருந்துகளும் காணப்படவில்லை.",
    noRefillsRecorded: "உங்களுக்கு பதிவு செய்யப்பட்ட மறு நிரப்பல்கள் எதுவும் இல்லை.",
    noRefillNeeded: "உங்கள் எந்த மருந்துக்கும் தற்போது மறு நிரப்பல் தேவைப்படவில்லை.",
    refillsLeft: "பதிவு செய்யப்பட்ட மறு நிரப்பல்கள்",
    remainingStock: "மீதமுள்ள இருப்பு",
    refillQuantity: "சேர்க்கப்பட்ட அளவு",
    refillDate: "தேதி",
    totalRefills: "மொத்த பதிவு செய்யப்பட்ட மறு நிரப்பல்கள்",
  },
};

const NOTIFICATION_REPLY_I18N = {
  english: {
    title: "Recent Notifications & Alerts:",
    titleLatest: "Latest Notifications & Alerts:",
    titleLast: "Last Notification:",
    titleUnread: "Unread Notifications & Alerts:",
    titleToday: "Today's Notifications & Alerts:",
    titleImportant: "Important Notifications & Alerts:",
    total: "Total Notifications",
    unread: "Unread",
    read: "Read",
    noNotifs: "You have no notifications.",
    noUnread: "You have no unread notifications.",
    noTodayNotifs: "You have no notifications for today.",
    noImportantNotifs: "You have no important notifications.",
  },
  gujarati: {
    title: "તાજેતરના નોટિફિકેશન અને અલર્ટ:",
    titleLatest: "તાજેતરના નોટિફિકેશન અને અલર્ટ:",
    titleLast: "છેલ્લી નોટિફિકેશન:",
    titleUnread: "ન વંચાયેલ નોટિફિકેશન:",
    titleToday: "આજના નોટિફિકેશન:",
    titleImportant: "મહત્વપૂર્ણ નોટિફિકેશન:",
    total: "કુલ નોટિફિકેશન",
    unread: "ન વંચાયેલ",
    read: "વંચાયેલ",
    noNotifs: "તમારી પાસે કોઈ નોટિફિકેશન નથી.",
    noUnread: "તમારી પાસે કોઈ ન વંચાયેલ નોટિફિકેશન નથી.",
    noTodayNotifs: "તમારી પાસે આજ માટે કોઈ નોટિફિકેશન નથી.",
    noImportantNotifs: "તમારી પાસે કોઈ મહત્વપૂર્ણ નોટિફિકેશન નથી.",
  },
  hindi: {
    title: "हाल की सूचनाएं और अलर्ट:",
    titleLatest: "नवीनतम सूचनाएं और अलर्ट:",
    titleLast: "आखिरी सूचना:",
    titleUnread: "अपठित सूचनाएं:",
    titleToday: "आज की सूचनाएं:",
    titleImportant: "महत्वपूर्ण सूचनाएं:",
    total: "कुल सूचनाएं",
    unread: "अपठित",
    read: "पढ़ी गई",
    noNotifs: "आपकी कोई सूचना नहीं है।",
    noUnread: "आपकी कोई अपठित सूचना नहीं है।",
    noTodayNotifs: "आपकी आज के लिए कोई सूचना नहीं है।",
    noImportantNotifs: "आपकी कोई महत्वपूर्ण सूचना नहीं है।",
  },
  marathi: {
    title: "अलीकडील सूचना आणि सूचना:",
    titleLatest: "नवीनतम सूचना आणि अलर्ट:",
    titleLast: "शेवटची सूचना:",
    titleUnread: "न वाचलेल्या सूचना:",
    titleToday: "आजच्या सूचना:",
    titleImportant: "महत्त्वाच्या सूचना:",
    total: "एकूण सूचना",
    unread: "न वाचलेले",
    read: "वाचलेले",
    noNotifs: "तुमच्याकडे कोणत्याही सूचना नाहीत.",
    noUnread: "तुमच्याकडे कोणत्याही न वाचलेल्या सूचना नाहीत.",
    noTodayNotifs: "तुमच्याकडे आजसाठी कोणतीही सूचना नाही.",
    noImportantNotifs: "तुमच्याकडे कोणत्याही महत्त्वाच्या सूचना नाहीत.",
  },
  tamil: {
    title: "சமீபத்திய அறிவிப்புகள் மற்றும் எச்சரிக்கைகள்:",
    titleLatest: "சமீபத்திய அறிவிப்புகள் மற்றும் எச்சரிக்கைகள்:",
    titleLast: "கடைசி அறிவிப்பு:",
    titleUnread: "படிக்காத அறிவிப்புகள்:",
    titleToday: "இன்றைய அறிவிப்புகள்:",
    titleImportant: "முக்கியமான அறிவிப்புகள்:",
    total: "மொத்த அறிவிப்புகள்",
    unread: "படிக்காதவை",
    read: "படித்தவை",
    noNotifs: "உங்களுக்கு அறிவிப்புகள் எதுவும் இல்லை.",
    noUnread: "உங்களுக்கு படிக்காத அறிவிப்புகள் எதுவும் இல்லை.",
    noTodayNotifs: "இன்று உங்களுக்கு அறிவிப்புகள் எதுவும் இல்லை.",
    noImportantNotifs: "உங்களுக்கு முக்கியமான அறிவிப்புகள் எதுவும் இல்லை.",
  },
};

const COUNT_REPLY_I18N = {
  english: {
    documents: (count) => `You have ${count} uploaded medical document(s).`,
    medications: (count) => `You have ${count} active medication(s).`,
    notifications: (total, unread) => `You have ${total} notification(s) (${unread} unread).`,
    reminders: (total, taken, missed, pending) =>
      `You have ${total} scheduled dose(s) (${taken} taken, ${missed} missed, ${pending} pending).`,
    refills: (count) =>
      count > 0
        ? `You have ${count} recorded medication refill(s).`
        : "You have no recorded medication refills.",
  },
  gujarati: {
    documents: (count) => `તમારી પાસે ${count} અપલોડ કરેલ મેડિકલ દસ્તાવેજ(ઓ) છે.`,
    medications: (count) => `તમારી પાસે ${count} ચાલુ દવા(ઓ) છે.`,
    notifications: (total, unread) => `તમારી પાસે ${total} નોટિફિકેશન છે (${unread} ન વંચાયેલ).`,
    reminders: (total, taken, missed, pending) =>
      `તમારી પાસે ${total} નિર્ધારિત ડોઝ છે (${taken} લીધેલ, ${missed} ચૂકી ગયેલ, ${pending} બાકી).`,
    refills: (count) =>
      count > 0
        ? `તમારી પાસે ${count} નોંધાયેલ દવા રિફિલ છે.`
        : "તમારી પાસે કોઈ નોંધાયેલ રિફિલ નથી.",
  },
  hindi: {
    documents: (count) => `आपके पास ${count} अपलोड किए गए मेडिकल दस्तावेज़ हैं।`,
    medications: (count) => `आपकी ${count} सक्रिय दवाइयां हैं।`,
    notifications: (total, unread) => `आपके पास ${total} सूचनाएं हैं (${unread} अपठित)।`,
    reminders: (total, taken, missed, pending) =>
      `आपकी ${total} निर्धारित खुराक हैं (${taken} ली गई, ${missed} छूटी हुई, ${pending} लंबित)।`,
    refills: (count) =>
      count > 0 ? `आपके पास ${count} दर्ज दवा रिफिल हैं।` : "आपकी कोई दर्ज रिफिल नहीं है।",
  },
  marathi: {
    documents: (count) => `तुमच्याकडे ${count} अपलोड केलेले वैद्यकीय दस्तऐवज आहेत.`,
    medications: (count) => `तुमच्याकडे ${count} चालू औषधे आहेत.`,
    notifications: (total, unread) => `तुमच्याकडे ${total} सूचना आहेत (${unread} न वाचलेले).`,
    reminders: (total, taken, missed, pending) =>
      `तुमच्याकडे ${total} नियोजित डोस आहेत (${taken} घेतलेले, ${missed} चुकलेले, ${pending} प्रलंबित).`,
    refills: (count) =>
      count > 0
        ? `तुमच्याकडे ${count} नोंदवलेले औषध रिफिल आहेत.`
        : "तुमच्याकडे कोणतेही नोंदवलेले रिफिल नाही.",
  },
  tamil: {
    documents: (count) => `உங்களிடம் ${count} பதிவேற்றப்பட்ட மருத்துவ ஆவணங்கள் உள்ளன.`,
    medications: (count) => `உங்களிடம் ${count} செயலில் உள்ள மருந்துகள் உள்ளன.`,
    notifications: (total, unread) =>
      `உங்களிடம் ${total} அறிவிப்புகள் உள்ளன (${unread} படிக்காதவை).`,
    reminders: (total, taken, missed, pending) =>
      `உங்களிடம் ${total} திட்டமிடப்பட்ட மருந்தளவுகள் உள்ளன (${taken} எடுத்துக்கொண்டவை, ${missed} தவறவிட்டவை, ${pending} நிலுவையில் உள்ளவை).`,
    refills: (count) =>
      count > 0
        ? `உங்களிடம் ${count} பதிவு செய்யப்பட்ட மருந்து மறு நிரப்பல்கள் உள்ளன.`
        : "உங்களுக்கு பதிவு செய்யப்பட்ட மறு நிரப்பல்கள் எதுவும் இல்லை.",
  },
};

const MEDICATION_REPLY_I18N = {
  english: {
    titleAll: "Your Medications:",
    titleCurrent: "Your Current Medications:",
    titleMorning: "Morning Medications:",
    titleNight: "Night Medications:",
    titleBeforeFood: "Medicines to Take Before Food:",
    titleAfterFood: "Medicines to Take After Food:",
    titleActive: "Active Medications:",
    titleInactive: "Inactive/Past Medications:",
    titleDosage: "Medication Dosages:",
    titleSchedule: "Medication Schedule:",
    noMeds: "You have no medications recorded.",
    noMorningMeds: "You have no medications scheduled for the morning.",
    noNightMeds: "You have no medications scheduled for the night.",
    noBeforeFoodMeds: "You have no medications to take before food.",
    noAfterFoodMeds: "You have no medications to take after food.",
    noActiveMeds: "You have no active medications.",
    noInactiveMeds: "You have no inactive medications.",
    noDosage: "No dosage instructions found.",
    noSchedule: "No schedule timing found.",
    dosageLabel: "Dose",
    frequencyLabel: "Frequency",
    scheduleLabel: "Timing",
    instructionLabel: "Food",
    endDateLabel: "End Date",
    stockCompletedNote:
      "Note: This medication is completed/inactive because its stock is 0 and not restocked. Adding a refill will reactivate it.",
  },
  gujarati: {
    titleAll: "તમારી દવાઓની યાદી:",
    titleCurrent: "તમારી ચાલુ દવાઓ:",
    titleMorning: "સવારની દવાઓ:",
    titleNight: "રાત્રિની દવાઓ:",
    titleBeforeFood: "જમતા પહેલાં લેવાની દવાઓ:",
    titleAfterFood: "જમ્યા પછી લેવાની દવાઓ:",
    titleActive: "ચાલુ (એક્ટિવ) દવાઓ:",
    titleInactive: "બંધ (અગાઉની) દવાઓ:",
    titleDosage: "દવાઓનો ડોઝ:",
    titleSchedule: "દવાઓ લેવાનો સમય:",
    noMeds: "તમારી કોઈ દવા નોંધાયેલ નથી.",
    noMorningMeds: "સવાર માટે કોઈ દવા નિર્ધારિત નથી.",
    noNightMeds: "રાત માટે કોઈ દવા નિર્ધારિત નથી.",
    noBeforeFoodMeds: "જમતા પહેલા લેવા માટે કોઈ દવા નથી.",
    noAfterFoodMeds: "જમ્યા પછી લેવા માટે કોઈ દવા નથી.",
    noActiveMeds: "તમારી કોઈ સક્રિય દવા નથી.",
    noInactiveMeds: "તમારી કોઈ અગાઉની દવા નથી.",
    noDosage: "ડોઝની વિગતો મળી નથી.",
    noSchedule: "સમયપત્રક મળ્યું નથી.",
    dosageLabel: "ડોઝ",
    frequencyLabel: "આવૃત્તિ",
    scheduleLabel: "સમય",
    instructionLabel: "ખોરાક",
    endDateLabel: "અંતિમ તારીખ",
    stockCompletedNote:
      "નોંધ: આ દવાનો સ્ટોક પૂરો થઈ ગયો છે (0 બાકી) તેથી તે નિષ્ક્રિય/પૂર્ણ છે. રિફિલ ઉમેરવાથી તે ફરીથી સક્રિય થશે.",
  },
  hindi: {
    titleAll: "आपकी दवाइयों की सूची:",
    titleCurrent: "आपकी वर्तमान दवाइयां:",
    titleMorning: "सुबह की दवाइयां:",
    titleNight: "रात की दवाइयां:",
    titleBeforeFood: "भोजन से पहले ली जाने वाली दवाइयां:",
    titleAfterFood: "भोजन के बाद ली जाने वाली दवाइयां:",
    titleActive: "सक्रिय दवाइयां:",
    titleInactive: "निष्क्रिय/पुरानी दवाइयां:",
    titleDosage: "दवाइयों की खुराक (डोज़):",
    titleSchedule: "दवाइयों का समय:",
    noMeds: "आपकी कोई दवाई दर्ज नहीं है।",
    noMorningMeds: "सुबह के लिए कोई दवाई निर्धारित नहीं है।",
    noNightMeds: "रात के लिए कोई दवाई निर्धारित नहीं है।",
    noBeforeFoodMeds: "भोजन से पहले लेने वाली कोई दवाई नहीं है।",
    noAfterFoodMeds: "भोजन के बाद लेने वाली कोई दवाई नहीं है।",
    noActiveMeds: "आपकी कोई सक्रिय दवाई नहीं है।",
    noInactiveMeds: "आपकी कोई पुरानी दवाई नहीं है।",
    noDosage: "खुराक का विवरण नहीं मिला।",
    noSchedule: "समय सारिणी नहीं मिली।",
    dosageLabel: "खुराक",
    frequencyLabel: "आवृत्ति",
    scheduleLabel: "समय",
    instructionLabel: "भोजन",
    endDateLabel: "अंतिम तिथि",
    stockCompletedNote:
      "नोट: इस दवा का स्टॉक समाप्त हो गया है (0 शेष) इसलिए यह निष्क्रिय/पूर्ण है। रिफिल जोड़ने पर यह फिर से सक्रिय हो जाएगी।",
  },
  marathi: {
    titleAll: "तुमची औषधांची यादी:",
    titleCurrent: "तुमची सध्याची औषधे:",
    titleMorning: "सकाळची औषधे:",
    titleNight: "रात्रीची औषधे:",
    titleBeforeFood: "जेवणापूर्वी घ्यायची औषधे:",
    titleAfterFood: "जेवणानंतर घ्यायची औषधे:",
    titleActive: "चालू औषधे:",
    titleInactive: "बंद/मागील औषधे:",
    titleDosage: "औषधांचा डोस:",
    titleSchedule: "औषधांची वेळ:",
    noMeds: "तुमची कोणतीही औषधे नोंदवलेली नाहीत.",
    noMorningMeds: "सकाळसाठी कोणतीही औषधे नियोजित नाहीत.",
    noNightMeds: "रात्रीसाठी कोणतीही औषधे नियोजित नाहीत.",
    noBeforeFoodMeds: "जेवणापूर्वी घेण्यासारखे कोणतेही औषध नाही.",
    noAfterFoodMeds: "जेवणानंतर घेण्यासारखे कोणतेही औषध नाही.",
    noActiveMeds: "तुमची कोणतीही चालू औषधे नाहीत.",
    noInactiveMeds: "तुमची कोणतीही मागील औषधे नाहीत.",
    noDosage: "डोस तपशील सापडला नाही.",
    noSchedule: "वेळापत्रक सापडले नाही.",
    dosageLabel: "डोस",
    frequencyLabel: "वारंवारता",
    scheduleLabel: "वेळ",
    instructionLabel: "अन्न",
    endDateLabel: "शेवटची तारीख",
    stockCompletedNote:
      "टीप: या औषधाचा साठा संपला आहे (0 शिल्लक) त्यामुळे ते निष्क्रिय/पूर्ण आहे. रिफिल जोडल्यास ते पुन्हा सक्रिय होईल.",
  },
  tamil: {
    titleAll: "உங்கள் மருந்துகளின் பட்டியல்:",
    titleCurrent: "உங்கள் தற்போதைய மருந்துகள்:",
    titleMorning: "காலை மருந்துகள்:",
    titleNight: "இரவு மருந்துகள்:",
    titleBeforeFood: "உணவுக்கு முன் உட்கொள்ள வேண்டிய மருந்துகள்:",
    titleAfterFood: "உணவுக்குப் பின் உட்கொள்ள வேண்டிய மருந்துகள்:",
    titleActive: "செயலில் உள்ள மருந்துகள்:",
    titleInactive: "செயலற்ற/முந்தைய மருந்துகள்:",
    titleDosage: "மருந்தளவு விவரங்கள்:",
    titleSchedule: "மருந்து உட்கொள்ளும் நேரம்:",
    noMeds: "உங்கள் மருந்துகள் எதுவும் பதிவு செய்யப்படவில்லை.",
    noMorningMeds: "காலைக்கு எந்த மருந்துகளும் திட்டமிடப்படவில்லை.",
    noNightMeds: "இரவுக்கு எந்த மருந்துகளும் திட்டமிடப்படவில்லை.",
    noBeforeFoodMeds: "உணவுக்கு முன் எடுத்துக்கொள்ள மருந்துகள் இல்லை.",
    noAfterFoodMeds: "உணவுக்குப் பின் எடுத்துக்கொள்ள மருந்துகள் இல்லை.",
    noActiveMeds: "செயலில் உள்ள மருந்துகள் எதுவும் இல்லை.",
    noInactiveMeds: "முந்தைய மருந்துகள் எதுவும் இல்லை.",
    noDosage: "மருந்தளவு விவரங்கள் கிடைக்கவில்லை.",
    noSchedule: "நேர அட்டவணை கிடைக்கவில்லை.",
    dosageLabel: "மருந்தளவு",
    frequencyLabel: "அதிர்வெண்",
    scheduleLabel: "நேரம்",
    instructionLabel: "உணவு",
    endDateLabel: "முடிவு தேதி",
    stockCompletedNote:
      "குறிப்பு: இந்த மருந்தின் கையிருப்பு முடிந்ததால் (0 மீதம்) செயலற்றதாக உள்ளது. ரீஃபில் சேர்த்தால் இது மீண்டும் செயலில் வரும்.",
  },
};

const DOCUMENT_REPLY_I18N = {
  english: {
    title: "Your Medical Documents:",
    titleLatest: "Latest Medical Report:",
    titleFiltered: "Filtered Medical Documents:",
    noDocs: "You have no uploaded medical documents.",
    noMatchingDocs: "No matching medical documents found.",
    total: "Total Documents",
    fileName: "File Name",
    reportDate: "Date",
    category: "Category",
    status: "Status",
  },
  gujarati: {
    title: "તમારા મેડિકલ દસ્તાવેજો:",
    titleLatest: "છેલ્લો મેડિકલ રિપોર્ટ:",
    titleFiltered: "ફિલ્ટર કરેલ મેડિકલ દસ્તાવેજો:",
    noDocs: "તમારી પાસે કોઈ અપલોડ કરેલ મેડિકલ દસ્તાવેજ નથી.",
    noMatchingDocs: "કોઈ મેળ ખાતા મેડિકલ દસ્તાવેજ મળ્યા નથી.",
    total: "કુલ દસ્તાવેજો",
    fileName: "ફાઇલનું નામ",
    reportDate: "તારીખ",
    category: "કેટેગરી",
    status: "સ્થિતિ",
  },
  hindi: {
    title: "आपके मेडिकल दस्तावेज़:",
    titleLatest: "नवीनतम मेडिकल रिपोर्ट:",
    titleFiltered: "फ़िल्टर किए गए मेडिकल दस्तावेज़:",
    noDocs: "आपके पास कोई अपलोड किए गए मेडिकल दस्तावेज़ नहीं हैं।",
    noMatchingDocs: "कोई मेल खाने वाले मेडिकल दस्तावेज़ नहीं मिले।",
    total: "कुल दस्तावेज़",
    fileName: "फ़ाइल का नाम",
    reportDate: "तारीख",
    category: "श्रेणी",
    status: "स्थिति",
  },
  marathi: {
    title: "तुमचे वैद्यकीय दस्तऐवज:",
    titleLatest: "नवीनतम वैद्यकीय अहवाल:",
    titleFiltered: "फिल्टर केलेले वैद्यकीय दस्तऐवज:",
    noDocs: "तुमच्याकडे कोणतेही अपलोड केलेले वैद्यकीय दस्तऐवज नाहीत.",
    noMatchingDocs: "कोणतेही जुळणारे वैद्यकीय दस्तऐवज आढळले नाहीत.",
    total: "एकूण दस्तऐवज",
    fileName: "फाइलचे नाव",
    reportDate: "तारीख",
    category: "प्रवर्ग",
    status: "स्थिती",
  },
  tamil: {
    title: "உங்கள் மருத்துவ ஆவணங்கள்:",
    titleLatest: "சமீபத்திய மருத்துவ அறிக்கை:",
    titleFiltered: "வடிகட்டப்பட்ட மருத்துவ ஆவணங்கள்:",
    noDocs: "உங்களிடம் பதிவேற்றப்பட்ட மருத்துவ ஆவணங்கள் எதுவும் இல்லை.",
    noMatchingDocs: "பொருந்தும் மருத்துவ ஆவணங்கள் எதுவும் காணப்படவில்லை.",
    total: "மொத்த ஆவணங்கள்",
    fileName: "கோப்பு பெயர்",
    reportDate: "தேதி",
    category: "வகை",
    status: "நிலை",
  },
};

module.exports = {
  NO_CONTEXT_REPLY_I18N,
  REQUIRE_SELECTION_I18N,
  AGE_REPLY_I18N,
  AGE_KEYWORDS,
  SUMMARY_KEYWORDS,
  SUMMARY_LABELS_I18N,
  REPORT_PROCESSING_I18N,
  NO_REPORT_FOUND_I18N,
  NO_SUMMARY_AVAILABLE_I18N,
  PREDEFINED_QUESTIONS_I18N,
  PROFILE_REPLY_I18N,
  REMINDER_REPLY_I18N,
  REFILL_REPLY_I18N,
  NOTIFICATION_REPLY_I18N,
  COUNT_REPLY_I18N,
  MEDICATION_REPLY_I18N,
  DOCUMENT_REPLY_I18N,
};
