const messageConstants = Object.freeze({
  DOCUMENT_CREATED: "Document created successfully",
  DOCUMENT_DELETED: "Document deleted successfully",
  DOCUMENT_FETCHED: "Document fetched successfully",
  DOCUMENT_FILTERED_LIST_FETCHED: "fetch data successfully",
  DOCUMENT_LIST_FETCHED: "Document list fetched successfully",
  DOCUMENT_TYPE_IS_REQUIRED: "Document type is required",
  HEALTH_CHECK_SUCCESS: "Health check passed",
  NOTIFICATION_BADGE_COUNT_FETCHED: "fetch data successfully",
  NOTIFICATION_DELETED: "Notification deleted successfully",
  NOTIFICATION_LIST_FETCHED: "fetch data successfully",
  NOTIFICATION_MARKED_ALL_READ: "All notifications marked as read",
  NOTIFICATION_MARKED_READ: "Notification marked as read",
  NOTIFICATION_SENT: "Notification sent successfully",
  OTP_SENT: "OTP sent successfully",
  OTP_VERIFIED: "OTP verified successfully",
  PATIENT_CREATED: "Patient created successfully",
  PATIENT_DELETED: "Patient deleted successfully",
  PATIENT_FETCHED: "Patient fetched successfully",
  PATIENT_LIST_FETCHED: "Patient list fetched successfully",
  PATIENT_LOGGED_OUT: "Patient logged out successfully",
  PATIENT_LOGIN_SUCCESS: "Patient logged in successfully",
  PATIENT_PERMANENTLY_DELETED: "Patient permanently deleted successfully",
  PATIENT_UPDATED: "Patient updated successfully",
  PASSWORD_RESET_SUCCESS: "Password reset successfully",
  SESSION_CREATED: "Session created successfully",
  SESSION_FETCHED: "Session fetched successfully",
  TOKEN_REFRESHED: "Token refreshed successfully",
  PATIENT_PROFILE_FETCHED: "Patient profile fetched successfully",
  FILE_IS_REQUIRED: "File is required",
  DOCUMENT_DOWNLOAD_URL_FETCHED: "Document download URL fetched successfully",

  //medication
  MEDICATION_CREATED: "Medication created successfully",
  MEDICATION_DELETED: "Medication deleted successfully",
  MEDICATION_FETCHED: "Medication fetched successfully",
  MEDICATION_LIST_FETCHED: "Medication list fetched successfully",
  MEDICATION_UPDATED: "Medication updated successfully",
  MEDICATION_FILTERED_LIST_FETCHED: "Medication filtered list fetched successfully",
  MEDICATION_REMINDER_LIST_FETCHED: "Medication reminder list fetched successfully",
  MEDICATION_REMINDER_FETCHED: "Medication reminder fetched successfully",
  MEDICATION_REMINDER_DELETED: "Medication reminder deleted successfully",
  MEDICATION_OCCURRENCES_FETCHED: "Medication occurrences fetched successfully",
  MEDICATION_REMINDER_COMPLETED: "Medication reminder marked as completed",
  MEDICATION_REMINDER_SKIPPED: "Medication reminder marked as skipped",
  MEDICATION_REMINDER_MISSED: "Medication reminder marked as missed",
  EDICATION_REMINDER_SKIPPED: "Medication reminder marked as skipped",
  MEDICATION_REMINDER_SNOOZED: "Medication reminder snoozed",
  REFILL_ALERTS_FETCHED: "Refill alerts fetched successfully",
  TODAY_REFILL_ALERTS_FETCHED: "Today's refill alerts fetched successfully",
  REFILL_ALERT_COMPLETED: "Refill alert marked as completed",
  REFILL_ALERT_SNOOZED: "Refill alert snoozed",
  MEDICATION_REMINDER_CREATED: "Medication reminder created successfully",
  MEDICATION_OCCURRENCE_UPDATED: "Medication occurrence updated successfully",
});

module.exports = { messageConstants };
