from __future__ import annotations

# Canonical Stage Keys
STAGE_QUEUED = "QUEUED"
STAGE_VALIDATING = "VALIDATING"
STAGE_UPLOADING = "UPLOADING"
STAGE_OCR_RUNNING = "OCR_RUNNING"
STAGE_PARSING = "PARSING"
STAGE_GRAPH_EXTRACTION = "GRAPH_EXTRACTION"
STAGE_FIELD_EXTRACTION = "FIELD_EXTRACTION"
STAGE_ANALYZING = "ANALYZING"
STAGE_SUMMARIZING = "SUMMARIZING"
STAGE_EMBEDDING = "EMBEDDING"

# Canonical Stage Status Keys
STATUS_QUEUED = "QUEUED"
STATUS_IN_PROGRESS = "IN_PROGRESS"
STATUS_COMPLETED = "COMPLETED"
STATUS_FAILED = "FAILED"
STATUS_REJECTED = "REJECTED"

# Stage Progress Windows [start_pct, end_pct]
STAGE_PROGRESS_WINDOWS: dict[str, tuple[int, int]] = {
    STAGE_QUEUED: (0, 0),
    STAGE_VALIDATING: (0, 5),
    STAGE_UPLOADING: (5, 15),
    STAGE_OCR_RUNNING: (15, 55),
    STAGE_PARSING: (55, 60),
    STAGE_GRAPH_EXTRACTION: (60, 65),
    STAGE_FIELD_EXTRACTION: (65, 80),
    STAGE_ANALYZING: (80, 85),
    STAGE_SUMMARIZING: (85, 95),
    STAGE_EMBEDDING: (95, 100),
}

# Strict Pipeline Execution Order (9 core stages after QUEUED)
PIPELINE_STAGES_ORDER: list[str] = [
    STAGE_VALIDATING,
    STAGE_UPLOADING,
    STAGE_OCR_RUNNING,
    STAGE_PARSING,
    STAGE_GRAPH_EXTRACTION,
    STAGE_FIELD_EXTRACTION,
    STAGE_ANALYZING,
    STAGE_SUMMARIZING,
    STAGE_EMBEDDING,
]
