openapi: 3.0.0
info:
  title: Medication Reminder API
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    ReminderIdParam:
      in: path
      name: id
      required: true
      schema:
        type: string
        format: uuid

  schemas:
    ReminderOccurrenceStatus:
      type: string
      enum:
        - PENDING
        - COMPLETED

    ReminderTime:
      type: object

      properties:
        time:
          type: string
          example: "08:00"

        period:
          type: string
          enum:
            - AM
            - PM

    MedicationReminder:
      type: object

      properties:
        id:
          type: string
          format: uuid

        patientId:
          type: string
          format: uuid

        medicationId:
          type: string
          format: uuid

        medicationName:
          type: string
          example: Paracetamol

        medicationType:
          type: string
          example: TABLET

        reminderBeforeMinutes:
          type: integer
          example: 5

        afterReminderMinutes:
          type: integer
          example: 10

        refillAlertBeforeDays:
          type: integer
          example: 1

        dosePerIntake:
          type: integer
          example: 1

        routineBase:
          type: string
          example: ONCE_DAILY

        medicationTime:
          type: array

          items:
            $ref: "#/components/schemas/ReminderTime"

        active:
          type: boolean
          example: true

        createdAt:
          type: string
          format: date-time

        updatedAt:
          type: string
          format: date-time

    MedicationReminderOccurrence:
      type: object

      properties:
        id:
          type: string
          format: uuid

        reminderId:
          type: string
          format: uuid

        medicationId:
          type: string
          format: uuid

        medicationName:
          type: string
          example: Paracetamol

        medicationType:
          type: string
          example: TABLET

        status:
          $ref: "#/components/schemas/ReminderOccurrenceStatus"

        actualMedicationTime:
          type: string
          format: date-time

        beforeReminderTime:
          type: string
          format: date-time

        afterReminderTime:
          type: string
          format: date-time

        completedAt:
          type: string
          nullable: true
          format: date-time

        notificationSent:
          type: boolean
          example: false

        notificationSentAt:
          type: string
          nullable: true
          format: date-time

        createdAt:
          type: string
          format: date-time

    CreateReminderRequest:
      type: object

      required:
        - medicationId

      properties:
        medicationId:
          type: string
          format: uuid

        reminderBeforeMinutes:
          type: integer
          minimum: 0
          default: 5
          example: 5

        afterReminderMinutes:
          type: integer
          minimum: 1
          default: 10
          example: 10

        refillAlertBeforeDays:
          type: integer
          minimum: 1
          default: 1
          example: 1

    ListOccurrencesRequest:
      type: object

      properties:
        filter:
          type: object

          properties:
            status:
              $ref: "#/components/schemas/ReminderOccurrenceStatus"

            startDate:
              type: string
              format: date

            endDate:
              type: string
              format: date

            medicationName:
              type: string
              example: Paracetamol

            medicationType:
              type: string
              example: TABLET

            date:
              type: string
              format: date
              example: "2026-05-28"

        sort:
          type: object

          properties:
            sortBy:
              type: string

              enum:
                - actualMedicationTime
                - completedAt
                - createdAt
                - status

              default: actualMedicationTime

            sortOrder:
              type: string

              enum:
                - asc
                - desc

              default: asc

        page:
          type: object

          properties:
            pageNumber:
              type: integer
              default: 1
              example: 1

            pageLimit:
              type: integer
              default: 10
              example: 10

    UpdateOccurrenceRequest:
      type: object

      required:
        - status

      properties:
        status:
          type: string
          enum:
            - COMPLETED

paths:
  /medication-reminders/create:
    post:
      tags:
        - Medication Reminder

      summary: Create medication reminder

      security:
        - bearerAuth: []

      requestBody:
        required: true

        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateReminderRequest"

      responses:
        "201":
          description: Medication reminder created successfully

        "400":
          description: Validation error

        "401":
          description: Unauthorized

        "404":
          description: Medication not found

  /medication-reminders:
    get:
      tags:
        - Medication Reminder

      summary: Get all main reminders

      security:
        - bearerAuth: []

      responses:
        "200":
          description: Main reminders fetched successfully

        "401":
          description: Unauthorized

  /medication-reminders/occurrences:
    get:
      tags:
        - Medication Reminder Occurrence

      summary: Get all sub reminder occurrences

      security:
        - bearerAuth: []

      responses:
        "200":
          description: All occurrences fetched successfully

        "401":
          description: Unauthorized

  /medication-reminders/occurrences/list:
    post:
      tags:
        - Medication Reminder Occurrence

      summary: Filter reminder occurrences

      security:
        - bearerAuth: []

      requestBody:
        required: false

        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ListOccurrencesRequest"

      responses:
        "200":
          description: Reminder occurrences fetched successfully

        "400":
          description: Validation error

        "401":
          description: Unauthorized

  /medication-reminders/occurrences/today:
    get:
      tags:
        - Medication Reminder Occurrence

      summary: Get today occurrences

      security:
        - bearerAuth: []

      responses:
        "200":
          description: Today occurrences fetched successfully

        "401":
          description: Unauthorized

  /medication-reminders/occurrences/{id}:
    patch:
      tags:
        - Medication Reminder Occurrence

      summary: Update occurrence status

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/ReminderIdParam"

      requestBody:
        required: true

        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateOccurrenceRequest"

      responses:
        "200":
          description: Medication occurrence updated successfully

        "400":
          description: Validation error

        "401":
          description: Unauthorized

        "404":
          description: Occurrence not found

  /medication-reminders/{id}:
    delete:
      tags:
        - Medication Reminder

      summary: Soft delete medication reminder

      security:
        - bearerAuth: []

      parameters:
        - $ref: "#/components/parameters/ReminderIdParam"

      responses:
        "200":
          description: Medication reminder deleted successfully

        "401":
          description: Unauthorized

        "404":
          description: Reminder not found
